### ISSUE TITLE
Text widget tiny mce link form cuts off "target" label

### ISSUE THREAD

**Issue by meatwad5675** [netrivet/prophoto-issues#134] opened 2016-01-13 19:41 UTC
https://prophoto6.zendesk.com/agent/tickets/450
![tiny_mce_link_form_bug](https://cloud.githubusercontent.com/assets/11544705/12305612/aed39a8e-ba03-11e5-833e-f002d7e4053f.png)

**Comment by lalunecreative** [comment] 2016-02-24 19:04
Easy for this one.. just have the text display above the fields or even better would be to have the text display IN the fields and just dissapear when people go to type.

**Comment by brianium** [comment] 2017-04-20 19:30
Easy would be great! 

This is one of our oldest bugs and its caused by TinyMCE. It uses JavaScript to position everything with inline styles ¯\\\_(ツ)_/¯. So it is actually quite impossible for us to make any sane change to it. 

I'm going to close this as there doesn't seem to be anything we can do about it at the moment.

**Closed by brianium** 2017-04-20 19:30 UTC
Labels: bug

**Comment by lalunecreative** [comment] 2017-04-20 19:39
My designer brain - ![giphy](https://cloud.githubusercontent.com/assets/17013471/25249329/c4e5795e-25ce-11e7-80a1-d1632eee3b41.gif)

**Comment by brianium** [comment] 2017-04-20 20:00
@lalunecreative lol I hear you man. Maybe we can rely on a new link plugin for tinymce in the future. Or not use tinymce at all. So many possibilities and hopes for the future!
