### ISSUE TITLE
Add lazyloading options

### ISSUE THREAD

**Issue by photog0411** [netrivet/prophoto-issues#482] opened 2016-04-16 20:43 UTC
And maybe a nice idea would be lazy loading for slideshow galleries with lots of images. It could lazy load the first 5 Images and load the rest on the background for those on slower connections viewing galleries with lots of images.

**Comment by jaredh159** [comment] 2016-04-17 12:46
@photog0411 Galleries already work like this.  They load at most 6 images, and the rest are requested in the background via ajax.  I'm gonna close this ticket as a duplicate of https://github.com/netrivet/prophoto-issues/issues/410, but thanks for the feedback!

**Closed by jaredh159** 2016-04-17 12:46 UTC
