### ISSUE TITLE
Script or heavily slanted fonts getting cut off in tile text layers

### ISSUE THREAD

**Issue by meatwad5675** [netrivet/prophoto-issues#582] opened 2016-06-15 17:26 UTC

**Comment by lalunecreative** [comment] 2016-06-15 17:54
Duplicate of this one, which is the oldest bug you guys currently have - https://github.com/netrivet/prophoto-issues/issues/127

**Comment by lalunecreative** [comment] 2016-06-15 17:55
It's basically just for script fonts in general, everywhere in ProPhoto, it effects tiles, grids, and font styles. I've tested them in all 3.

**Comment by brianclaryphoto** [comment] 2016-06-16 01:57
Glad I wasn't going crazy. I saw this but assumed it was something I had done :)

**Comment by brianium** [comment] 2016-06-16 15:38
This issue just got fixed in the 6.3 branch - if we have other script font woes, we can move this conversation over to #127

**Comment by brianium** [comment] 2016-06-16 15:39
Just to clarify, we fixed it specifically for tiles

**Comment by lalunecreative** [comment] 2016-06-16 15:48
Aw why not fix it for the rest too? : )

**Comment by brianium** [comment] 2016-06-16 15:51
That is definitely the plan :) - It's all these darn responsive nuances that make us break them up into separate issues.

**Comment by lalunecreative** [comment] 2016-06-16 15:54
That makes since, I always wondered why only part of something got worked on instead of just finishing it out.

**Comment by jaredh159** [comment] 2016-06-22 18:22
Released in 6.3.0.

**Closed by jaredh159** 2016-06-22 18:22 UTC
Labels: bug, tiles
